# Generated by Django 4.0.6 on 2023-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenProject', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('titleProject', models.CharField(max_length=150)),
                ('contentProject', models.TextField()),
                ('pdfProject', models.FileField(blank=True, null=True, upload_to='project_pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
                ('percent', models.PositiveSmallIntegerField()),
                ('knowledge', models.TextField(blank=True)),
            ],
        ),
    ]
